### ISSUE TITLE
Add highlightjs support

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/cfml#127]
Exercism uses [highlightjs](https://highlightjs.org/) for syntax highlighting. Unfortunately, there is no support for this track at the moment (see the [supported languages](https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)).

To properly support syntax highlighting for this track, an official grammar should be created at https://github.com/highlightjs/highlight.js/tree/main/src/languages. Note that this grammar could be relatively minimal at first and can be expanded upon at a later time.

@joshgoebel has initimate knowledge of the code base and has graciously offered to be available for any questions.

See https://github.com/exercism/v3-launch/issues/36

**Comment by bdw429s** [comment]
For any examples using script syntax, a JS highlighter is usually pretty close.  XML or HTML will usually get close for the tag syntax, but I don't think CF tags are used for any of the problems here.
