### ISSUE TITLE
Sort exercise list

### ISSUE THREAD

**Issue by BNAndras** [exercism/cfml#208]
@ErikSchierboom, I'd like to organize the exercise list. We could do this alphabetically by exercise name or by binned difficulty (easy, medium, and hard) and then by exercise name. I prefer the latter personally so students don't need to scroll the whole list to find an easy exercise for example.

**Comment by ErikSchierboom** [comment]
By difficulty first is recommended.

**Comment by BNAndras** [comment]
Great, I'll PR something over the weekend.
