### ISSUE TITLE
Need lexer/syntax highlighting for CFML

### ISSUE THREAD

**Issue by bdw429s** [exercism/cfml#54]
The test files on the site need syntax highlighting. 
http://exercism.io/exercises/coldfusion/rna-transcription/test-suite

If the libraries in use do not currently support CF script (We shouldn't be using any tag-based code on Exercism unless there's exercises which template HTML :) ) then we can just alias a JavaScript lexer.  Those usually work pretty good out of the box for CF Script.

cc/ @kytrinyx

**Comment by kytrinyx** [comment]
We use rouge in exercism v1, and prism in exercism v2 (which is in beta). I'll add the mapping for rouge in the exercism/exercism.io codebase.

**Comment by kytrinyx** [comment]
Here's the issue for tracking which languages we have syntax highlighting for in the v2 prototype https://github.com/exercism/meta/issues/90

**Comment by bdw429s** [comment]
Looks like this is deployed and working correctly.  I'm seeing syntax highlighting on the submitted answers as well as the test suites when viewing an exercise.
