### ISSUE TITLE
Rename track to "CFML"

### ISSUE THREAD

**Issue by bdw429s** [exercism/cfml#59]
@kytrinyx  let's get this done with.  I understand that I need you to do each of these 3 steps:

* [x] rename the repository
* [x] add cfml track to trackler
* [x] deploy
* [x] update database records
* [x] remove coldfusion from trackler
* [x] deploy

Can you help take care of this?

**Comment by kytrinyx** [comment]
Yepp—I'll get this done in the next day or so.

**Comment by bdw429s** [comment]
Thanks @kytrinyx !

**Comment by kytrinyx** [comment]
I got the first part done today, should be able to wrap it up tomorrow.

**Comment by kytrinyx** [comment]
Done! I'll let you close this out when you've had a chance to look over things to make sure they seem reasonable to you.

I'm traveling at the moment, so will be slow to respond, but I'm trying to check critical Exercism stuff at least once a day.

**Comment by bdw429s** [comment]
Thanks @kytrinyx !
