### ISSUE TITLE
Rename deprecated file

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cfml#80]
👋 I was going to inline the deprecated file https://github.com/exercism/cfml/blob/master/docs/EXERCISE_README_INSERT.md, but @bdw429s mentioned that this track doesn't use the Configlet tool to generate READMEs for the exercises.

Would you all be willing to move this file? That would let me delete some deprecated code.

The canonical location is `$TRACK_ROOT/config/exercise-readme-insert.md`

**Comment by bdw429s** [comment]
Sure, we can rename the file and put it wherever you want.

**Comment by kytrinyx** [comment]
Thanks!

**Comment by bdw429s** [comment]
@kytrinyx before I hit merge, can you confirm if this is what you need?
https://github.com/exercism/cfml/pull/81

**Comment by kytrinyx** [comment]
This is exactly what I need! Thanks!
