### ISSUE TITLE
Syntax highlighting for cfml

### ISSUE THREAD

**Issue by jackhughesweb** [exercism/cfml#87]
This track has not yet specified the file format mapping 
for syntax highlighting in exercism/meta#90

Please provide a mapping of file formats used by your track
in exercism/meta#90 (e.g. md = markdown)

This issue can be closed after this is completed. (Apologies
if you've already done this - this issue was generated
automatically).

**Comment by bdw429s** [comment]
Hi @jackhughesweb , sorry, but I didn't realize any further input was needed from us.  I have added a comment to that issue.
