### ISSUE TITLE
Fix getting started instructions for cfml

### ISSUE THREAD

**Issue by jackhughesweb** [exercism/cfml#88]
Some exercise README templates contain links to pages which no longer exist in v2 Exercism.

For example, C++'s README template had a link to /languages/cpp for instructions on running tests. The correct URLs to use can be found in the "Still stuck?" sidebar of exercise pages on the live site. You'll need to join the track and go to the first exercise to see them.

Please update any broken links in the `config/exercise_readme.go.tmpl` file, and run `configlet generate .` to generate new exercise READMEs with the fixes.

Instructions for generating READMEs with configlet can be found at:
https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md#generating-a-readme

Instructions for installing configlet can be found at:
https://github.com/exercism/docs/blob/bc29a1884da6c401de6f3f211d03aabe53894318/language-tracks/launch/first-exercise.md#the-configlet-tool

Tracking exercism/exercism.io#4102

**Comment by bdw429s** [comment]
Note, the CFML track has its own readme generator task written in CFML which is ran like so:
```
box task run tasks/GenerateReadme :slug=hello-world
or
box task run tasks/GenerateReadme --:all --:force
```

@jackhughesweb Can you clarify if the CFML track actually has bad links as described above or is this ticket simply for the maintainers to check and close if nothing is to be done?  I did just fix a few unrelated links that changed recently as part of an external site update but I don't see any links that are broken right off related to V2.

**Comment by jackhughesweb** [comment]
I can't find any broken links in this repo, so I'm closing this issue

**Comment by bdw429s** [comment]
Thx @jackhughesweb
